ci: add inkex101

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -24,6 +24,7 @@ jobs:
         include:
           - { os: 'windows-latest', python-version: '3.10', inkscape-version: '1.1', continue-on-error: false }
           - { os: 'ubuntu-latest', python-version: '3.11', inkscape-version: 'TRUNK', continue-on-error: true }
+          - { os: 'ubuntu-latest', python-version: '3.9', inkscape-version: 'inkex==1.0.1', continue-on-error: false }
     continue-on-error: ${{ matrix.continue-on-error }}
 
     steps:
@@ -43,7 +44,7 @@ jobs:
         sudo add-apt-repository ppa:inkscape.dev/trunk -y  # inkscape DEV from https://launchpad.net/~inkscape.dev/+archive/ubuntu/trunk
         sudo apt-get update
     - name: 🐧 install Inkscape & umockdev
-      if: ${{ matrix.os == 'ubuntu-latest' && matrix.inkscape-version != 'TRUNK' }}
+      if: ${{ matrix.os == 'ubuntu-latest' && matrix.inkscape-version != 'TRUNK' && ! startsWith(matrix.inkscape-version, 'inkex') }}
       run: |
         sudo apt-get -y install inkscape umockdev
     - name: 🐧 install Inkscape TRUNK & umockdev
@@ -63,9 +64,14 @@ jobs:
       if: ${{ matrix.os == 'windows-latest' && matrix.inkscape-version == '1.2' }}
       run: |
         choco install -y inkscape
+    - name: install Inkex
+      if: ${{ startsWith(matrix.inkscape-version, 'inkex') }}
+      run: |
+        sudo apt-get -y install umockdev
+        pip install ${{ matrix.inkscape-version }}
     - name: inkscape version
       run: |
-        inkscape --version
+        inkscape --version || echo "inkscape not found"
     - name: install requirements
       run: |
         python -m pip install --upgrade pip
